/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hamza;

import power.wise.app.PowerWiseGUI;

/**
 *
 * @author apple
 */
public class ReportsMenuForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportsMenuForm.class.getName());

    /**
     * Creates new form ReportGUI
     */
    public ReportsMenuForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        headingLabel = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        lblSelector = new javax.swing.JLabel();
        cmbAppliance = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        btnGenerateReport1 = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        lblback = new javax.swing.JLabel();
        Icon1 = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setBackground(new java.awt.Color(26, 101, 26));

        headingLabel.setFont(new java.awt.Font("Futura", 0, 22)); // NOI18N
        headingLabel.setForeground(new java.awt.Color(255, 255, 255));
        headingLabel.setText("PowerWise –  Generate Reports");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSelector.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblSelector.setForeground(new java.awt.Color(242, 242, 242));
        lblSelector.setText("Select Appliance:");
        lblSelector.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));
        MainPanel.add(lblSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 110, 30));

        cmbAppliance.setForeground(new java.awt.Color(26, 101, 26));
        cmbAppliance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose appliance…", "Washing Machine", "Heater", "Laptop", "Fridge" }));
        cmbAppliance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbApplianceActionPerformed(evt);
            }
        });
        MainPanel.add(cmbAppliance, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, 30));

        btnBack.setBackground(new java.awt.Color(26, 101, 26));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        btnBack.setForeground(new java.awt.Color(242, 242, 242));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        MainPanel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 170, 70));

        btnGenerateReport1.setBackground(new java.awt.Color(26, 101, 26));
        btnGenerateReport1.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        btnGenerateReport1.setForeground(new java.awt.Color(242, 242, 242));
        btnGenerateReport1.setText("Generate Report");
        btnGenerateReport1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnGenerateReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReport1ActionPerformed(evt);
            }
        });
        MainPanel.add(btnGenerateReport1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 170, 70));

        lblStatus.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblStatus.setText("       Report Generated");
        lblStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        MainPanel.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 220, 60));

        lblback.setBackground(new java.awt.Color(26, 101, 26));
        lblback.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblback.setOpaque(true);
        MainPanel.add(lblback, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 330, 50));

        Icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/power/wise/app/icons/reportGenerate.png"))); // NOI18N
        MainPanel.add(Icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/power/wise/app/icons/ReportsBackground.jpg"))); // NOI18N
        MainPanel.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 750, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbApplianceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbApplianceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbApplianceActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new ReportGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnGenerateReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReport1ActionPerformed
        // TODO add your handling code here:
        new ViewReportForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGenerateReport1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and dibtnMainMenuform */
        java.awt.EventQueue.invokeLater(() -> new ReportsMenuForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icon1;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGenerateReport1;
    private javax.swing.JComboBox<String> cmbAppliance;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel lblSelector;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblback;
    // End of variables declaration//GEN-END:variables
}
